### ISSUE TITLE
Rails 5.2.0.rc1 support

### ISSUE THREAD

**Issue by mfazekas** [jasonfb/nondestructive_migrations#17]
Rails 5.2.0.rc1 had a significant refactoring on how the migrations work.

https://github.com/rails/rails/commit/a2827ec9811b5012e8e366011fd44c8eb53fc714#diff-8d3c44120f7b67ff79e2fbe6a40d0ad6

```
bin/rails data:migrate
```

Now returns an error:
```
NoMethodError: undefined method `migrate' for NondestructiveMigrator:Class
/Users/boga/.rvm/gems/ruby-2.4.0/gems/nondestructive_migrations-1.2/lib/tasks/data.rb:11:in `block (2 levels) in <main>'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.rc1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.rc1/lib/rails/command.rb:48:in `invoke'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.rc1/lib/rails/commands.rb:18:in `<main>'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/bootsnap-1.1.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `block in require'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/boga/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.rc1/lib/active_support/dependencies.rb:283:in `require'
bin/rails:9:in `<main>'
```

**Comment by jasonfb** [comment]
thank you for letting me know; have yet to test this with anything beyond what is stated as tested in the README.md
